"""new book.want_to_read field

Revision ID: 6815bf81c0f5
Revises: 897fec164fd8
Create Date: 2025-08-25 18:35:53.057533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6815bf81c0f5'
down_revision = '897fec164fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('want_to_read', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('want_to_read')

    # ### end Alembic commands ###
