"""add book.edition

Revision ID: 897fec164fd8
Revises: f38dd9bfd508
Create Date: 2025-08-21 13:29:20.991010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '897fec164fd8'
down_revision = 'f38dd9bfd508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edition', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('edition')

    # ### end Alembic commands ###
