"""new fields for author and book models

Revision ID: fb062c98002f
Revises: 
Create Date: 2025-08-20 18:57:30.231545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb062c98002f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('birth_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('death_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('publisher', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('isbn', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('genre')
        batch_op.drop_column('language')
        batch_op.drop_column('isbn')
        batch_op.drop_column('publisher')
        batch_op.drop_column('year')

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('death_year')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
